dist: trusty

sudo: required

language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"

install: pip install tox-travis

script: tox

services: postgresql

addons:
  postgresql: "9.5"

env:
  TEST_DB_HOST: "localhost"
  TEST_DB_NAME: "test"
  TEST_DB_USER: "postgres"
  TEST_DB_PASSWORD: ""
